import socket
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyVP=object
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyVL=None
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyLP=False
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyLV=set
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV=len
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPy=any
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP=print
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVy=ValueError
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyP=input
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV=int
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpy=range
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL=str
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyp=IOError
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyL=True
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLp=pow
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLy=sum
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPV=socket.SOCK_STREAM
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVLy=socket.AF_INET
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVLP=socket.socket
import random
WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL='AuctionClient'
class WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVyL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyVP):
 def __init__(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,host="localhost",port=8020,mybidderid=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyVL,verbose=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyLP):
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose=verbose
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVLP(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVLy,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPV)
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.connect((host,port))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyV=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyLV(""" '".,;:{}[]()""")
  if mybidderid:
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV(mybidderid)==0 or WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPy((c in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyV)for c in mybidderid):
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("""mybidderid cannot contain spaces or any of the following: '".,;:{}[]()!""")
    raise WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVy
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid=mybidderid
  else:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyP("Input team / player name : ").strip()
   while WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid)==0 or WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPy((c in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyV)for c in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid):
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyP("""You input an empty string or included a space  or one of these '".,;:{}[]() in your name which is not allowed (_ or / are all allowed)\n for example Emil_And_Nischal is okay\nInput team / player name: """).strip()
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.send(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid.encode("utf-8"))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.recv(5024).decode('utf_8')
  x=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV.split(" ")
  if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Have received response of %s"%' '.join(x))
  if(x[0]!="Not" and WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV)!=0):
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numberbidders=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[0])
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Number of bidders: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numberbidders)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numtypes=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[1])
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Number of types: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numtypes)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numitems=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[2])
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Items in auction: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numitems)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.maxbudget=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[3])
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Budget: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.maxbudget)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.neededtowin=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[4])
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Needed to win: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.neededtowin)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known="True"==x[5]
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Order known: %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.auctionlist=[]
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.winnerpays=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[6])
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Winner pays: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.winnerpays)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.values={}
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists={}
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLy=7
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.neededtowin>0:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.values=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyVL
    for i in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpy(7,7+(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numtypes*2),2):
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists[x[i]]=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[i+1])
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLy+=2
    if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Item types: %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists))
   else:
    for i in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpy(7,7+(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numtypes*3),3):
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists[x[i]]=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[i+1])
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.values[x[i]]=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[i+2])
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLy+=3
    if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Item types: %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists))
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Values: %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.values))
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known:
    for i in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpy(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLy,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLy+WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numitems):
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.auctionlist.append(x[i])
    if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Auction order: %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.auctionlist))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.send('connected '.encode("utf-8"))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.recv(5024).decode('utf_8')
  x=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV.split(" ")
  if x[0]!='players':
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Did not receive list of players!")
   raise WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyp
  if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV(x)!=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numberbidders+2:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Length of list of players received does not match numberbidders!")
   raise WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyp
  if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("List of players: %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL(' '.join(x[1:])))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.players=[]
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVpy in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpy(1,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numberbidders+1):
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.players.append(x[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVpy])
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.send('ready '.encode("utf-8"))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.standings={WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVpL:{WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyp:0 for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyp in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists}for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVpL in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.players}
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVpL in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.players:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVpL]["money"]=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.maxbudget
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPyV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy):
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL=[]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp=[]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLy=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyLP
  while not WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLy:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.recv(5024).decode('utf_8')
   x=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV.split(" ")
   if x[0]!="done":
    if x[0]=="selling":
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypV=x[1]
     if not WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known:
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.auctionlist.append(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypV)
     if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Item on sale is %s"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypV)
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypL=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPyL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.numberbidders,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.neededtowin,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.artists,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.values,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL),WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.auctionlist,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.players,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.standings,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.winnerpays)
     if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Bidding: %d"%WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypL)
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.send(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPpL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypL).encode("utf-8"))
     WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.recv(5024).decode('utf_8')
     x=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpLV.split(" ")
     if x[0]=="draw":
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL.append(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyVL)
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp.append(0)
     if x[0]=="winner":
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL.append(x[1])
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp.append(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[3]))
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.standings[x[1]][WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPypV]+=1
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.standings[x[1]]["money"]-=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(x[3])
   else:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLy=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyL
    if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.verbose:
     if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.mybidderid in x[1:-1]:
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("I won! Hooray!")
     else:
      WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP("Well, better luck next time...")
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.sock.close()
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPyL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays):
  if(wincondition>0)and(winnerpays==0)and WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known:
   return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPLy(numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays)
  if(wincondition>0)and(winnerpays==0)and not WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known:
   return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVPy(numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays)
  if(wincondition==0)and(winnerpays==0)and WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known:
   return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVPL(numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays)
  if(wincondition==0)and(winnerpays==1)and WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.order_known:
   return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVyP(numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays)
  return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy.WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPLV(standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money'])
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPLV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp):
  return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()+1)
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPLy(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays):
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyp=itemsinauction[rd]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL=0.98
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp=itemsinauction[rd:]
  i=0
  st=(numberbidders/WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLPV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp))
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV={'total':0}
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL][WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV['total']=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV['total']+WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLp(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL,i)+st*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy
   if WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]+WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLp(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL,i)+st*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy
   else:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLp(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL,i)+st*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy
   i=i+1
  r=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVp=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyp]/WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV['total']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVp
  f=0.1
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVp)
  i=0
  while WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyL:
   i=i+1
   if(i==10):
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp=50
    break
   if r<WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy)
    break
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy-WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy*f
   r=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()
  return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVPy(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays):
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyp=itemsinauction[rd]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL=0.98
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp=0
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV in artists.keys():
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp+artists[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]
  i=0
  st=(numberbidders/WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp)
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV={'total':0}
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV in artists.keys():
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL][WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyV=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL.count(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV['total']=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV['total']+(artists[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]-WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyV)*st*(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy+0.2)
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]=(artists[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]-WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyV)*st*(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpy+0.2)
  r=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVp=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyp]/WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLV['total']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVp
  f=0.1
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVp)
  i=0
  while WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPyL:
   i=i+1
   if(i==10):
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp=100
    break
   if r<WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy:
    WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy)
    break
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy-WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLVy*f
   r=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLVP(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp)
  return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVPL(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays):
  v=values[itemsinauction[rd]]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp=itemsinauction[rd:]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVy=1000*numberbidders-WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLy(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp)
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL=0
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL=0.97
  i=0
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL+values[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLp(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL,i)
   i=i+1
  r=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp=v*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp/WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL
  return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp)
 def WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpVyP(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpVy,numberbidders,wincondition,artists,values,rd,itemsinauction,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVyL,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp,WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL,players,standings,winnerpays):
  v=values[itemsinauction[rd]]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp=standings[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPpyL]['money']
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp=itemsinauction[rd:]
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVy=1000*numberbidders-WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLy(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPVLp)
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL=0
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL=0.97
  i=0
  for WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV in WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyLp:
   WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL+values[WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLpV]*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrVPLp(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVL,i)
   i=i+1
  r=WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpyPL()
  WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp=v*WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPyVp/WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpPVL
  return WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrpLyV(WnqsHdcYBAzXtkTxGUlDCmgRioMOfFNQEevIahKjbSwuJrPLyp)
# Created by pyminifier (https://github.com/liftoff/pyminifier)
