import socket
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfpA=object
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfpO=None
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfOA=False
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfOp=set
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp=len
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAf=any
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA=print
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpf=ValueError
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfA=raw_input
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp=int
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQf=range
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO=str
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfQ=IOError
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfO=True
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOQ=pow
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOf=sum
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAp=socket.SOCK_STREAM
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpOf=socket.AF_INET
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpOA=socket.socket
import random
ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO=random.random
class ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpfO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfpA):
 def __init__(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,host="localhost",port=8020,mybidderid=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfpO,verbose=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfOA):
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose=verbose
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpOA(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpOf,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAp)
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.connect((host,port))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfp=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfOp(""" '".,;:{}[]()""")
  if mybidderid:
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp(mybidderid)==0 or ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAf((c in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfp)for c in mybidderid):
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("""mybidderid cannot contain spaces or any of the following: '".,;:{}[]()!""")
    raise ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpf
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid=mybidderid
  else:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfA("Input team / player name : ").strip() 
   while ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid)==0 or ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAf((c in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfp)for c in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid):
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfA("""You input an empty string or included a space  or one of these '".,;:{}[]() in your name which is not allowed (_ or / are all allowed)\n for example Emil_And_Nischal is okay\nInput team / player name: """).strip()
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.send(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid.encode("utf-8"))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.recv(5024).decode('utf_8')
  x=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp.split(" ")
  if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Have received response of %s"%' '.join(x))
  if(x[0]!="Not" and ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp)!=0):
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numberbidders=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[0])
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Number of bidders: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numberbidders)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numtypes=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[1])
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Number of types: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numtypes)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numitems=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[2])
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Items in auction: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numitems)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.maxbudget=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[3])
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Budget: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.maxbudget)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.neededtowin=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[4])
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Needed to win: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.neededtowin)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known="True"==x[5]
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Order known: %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.auctionlist=[]
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.winnerpays=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[6])
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Winner pays: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.winnerpays)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.values={}
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists={}
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOf=7
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.neededtowin>0:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.values=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfpO
    for i in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQf(7,7+(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numtypes*2),2):
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists[x[i]]=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[i+1])
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOf+=2
    if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Item types: %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists))
   else:
    for i in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQf(7,7+(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numtypes*3),3):
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists[x[i]]=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[i+1])
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.values[x[i]]=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[i+2])
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOf+=3
    if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Item types: %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists))
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Values: %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.values))
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known:
    for i in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQf(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOf,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOf+ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numitems):
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.auctionlist.append(x[i])
    if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Auction order: %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.auctionlist))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.send('connected '.encode("utf-8"))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.recv(5024).decode('utf_8')
  x=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp.split(" ")
  if x[0]!='players':
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Did not receive list of players!")
   raise ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfQ
  if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp(x)!=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numberbidders+2:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Length of list of players received does not match numberbidders!")
   raise ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfQ
  if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("List of players: %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO(' '.join(x[1:])))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.players=[]
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApQf in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQf(1,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numberbidders+1):
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.players.append(x[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApQf])
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.send('ready '.encode("utf-8"))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.standings={ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApQO:{ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfQ:0 for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfQ in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists}for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApQO in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.players}
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApQO in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.players:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApQO]["money"]=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.maxbudget
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAfp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf):
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO=[]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ=[]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOf=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfOA
  while not ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOf:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.recv(5024).decode('utf_8')
   x=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp.split(" ")
   if x[0]!="done":
    if x[0]=="selling":
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQp=x[1]
     if not ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known:
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.auctionlist.append(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQp)
     if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Item on sale is %s"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQp)
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQO=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAfO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.numberbidders,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.neededtowin,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.artists,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.values,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO),ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.auctionlist,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.players,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.standings,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.winnerpays)
     if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Bidding: %d"%ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQO)
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.send(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAQO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQO).encode("utf-8"))
     ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.recv(5024).decode('utf_8')
     x=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQOp.split(" ")
     if x[0]=="draw":
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO.append(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfpO)
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ.append(0)
     if x[0]=="winner":
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO.append(x[1])
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ.append(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[3]))
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.standings[x[1]][ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfQp]+=1
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.standings[x[1]]["money"]-=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(x[3])
   else:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOf=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfO
    if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.verbose:
     if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.mybidderid in x[1:-1]:
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("I won! Hooray!")
     else:
      ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA("Well, better luck next time...")
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.sock.close()
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAfO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays):
  if(wincondition>0)and(winnerpays==0)and ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known:
   return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAOf(numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays)
  if(wincondition>0)and(winnerpays==0)and not ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known:
   return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpAf(numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays)
  if(wincondition==0)and(winnerpays==0)and ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known:
   return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpAO(numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays)
  if(wincondition==0)and(winnerpays==1)and ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.order_known:
   return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpfA(numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays)
  return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf.ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAOp(standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money'])
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAOp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ):
  return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()+1)
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQAOf(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays):
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfQ=itemsinauction[rd]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO=0.98
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ=itemsinauction[rd:]
  i=0
  st=(numberbidders/ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOAp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ))
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp={'total':0}
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO][ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp['total']=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp['total']+ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOQ(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO,i)+st*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf
   if ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]+ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOQ(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO,i)+st*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf
   else:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOQ(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO,i)+st*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf
   i=i+1
  r=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpQ=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfQ]/ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp['total']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpQ
  f=0.1
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpQ)
  i=0
  while ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfO:
   i=i+1
   if(i==10):
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ=50
    break
   if r<ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf)
    break
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf-ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf*f
   r=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()
  return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpAf(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays):
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfQ=itemsinauction[rd]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO=0.98
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ=0
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp in artists.keys():
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ+artists[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]
  i=0
  st=(numberbidders/ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ)
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp={'total':0}
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp in artists.keys():
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO][ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfp=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO.count(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp['total']=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp['total']+(artists[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]-ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfp)*st*(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf+0.2)
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]=(artists[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]-ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfp)*st*(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQf+0.2)
  r=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpQ=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfQ]/ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOp['total']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpQ
  f=0.1
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpQ)
  i=0
  while ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAfO:
   i=i+1
   if(i==10):
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ=100
    break
   if r<ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf:
    ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf)
    break
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf-ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOpf*f
   r=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOpA(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ)
  return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpAO(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays):
  v=values[itemsinauction[rd]]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ=itemsinauction[rd:]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApf=1000*numberbidders-ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOf(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ)
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO=0
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO=0.97
  i=0
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO+values[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOQ(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO,i)
   i=i+1
  r=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ=v*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ/ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO
  return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ)
 def ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQpfA(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQpf,numberbidders,wincondition,artists,values,rd,itemsinauction,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApfO,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ,ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO,players,standings,winnerpays):
  v=values[itemsinauction[rd]]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ=standings[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAQfO]['money']
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ=itemsinauction[rd:]
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApf=1000*numberbidders-ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOf(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcApOQ)
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO=0
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO=0.97
  i=0
  for ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp in ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfOQ:
   ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO+values[ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOQp]*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcpAOQ(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpO,i)
   i=i+1
  r=ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQfAO()
  ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ=v*ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAfpQ/ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQApO
  return ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcQOfp(ihsFSkGBIrVHjMeKuxYbzvCnlmdEgaXqWNtLyowRDPJTUcAOfQ)
# Created by pyminifier (https://github.com/liftoff/pyminifier)
